import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { 
  ArrowLeft, 
  Save, 
  Image as ImageIcon, 
  Sparkles,
  Loader2,
  Eye
} from 'lucide-react';
import { api } from '../../services/api';
import { toast } from 'react-hot-toast';
import { useNavigate, useParams } from 'react-router-dom';

interface BlogData {
  title: string;
  excerpt: string;
  content: string;
  category: string;
  image: string;
  author: string;
  readTime: string;
  tags: string[];
  status: 'published' | 'draft';
}

const BlogEditor: React.FC = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [generatingAi, setGeneratingAi] = useState(false);
  const [formData, setFormData] = useState<BlogData>({
    title: '',
    excerpt: '',
    content: '',
    category: '',
    image: '',
    author: 'Admin',
    readTime: '5 min read',
    tags: [],
    status: 'draft'
  });

  useEffect(() => {
    if (id) {
      fetchBlog();
    }
  }, [id]);

  const fetchBlog = async () => {
    try {
      setLoading(true);
      const response = await api.getBlog(id!);
      if (response.success) {
        setFormData(response.data);
      }
    } catch (error) {
      toast.error('Failed to load blog post');
      navigate('/admin/blogs');
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      if (id) {
        await api.updateBlog(id, formData);
        toast.success('Blog post updated successfully');
      } else {
        await api.createBlog(formData);
        toast.success('Blog post created successfully');
      }
      navigate('/admin/blogs');
    } catch (error) {
      toast.error('Failed to save blog post');
    }
  };

  const handleGenerateContent = async () => {
    if (!formData.title) {
      toast.error('Please enter a title first');
      return;
    }
    
    setGeneratingAi(true);
    try {
      const response = await api.generateBlogContent(
        formData.title, 
        `Write a comprehensive blog post about ${formData.title} in the category of ${formData.category || 'Technology'}. Include an introduction, key points, and a conclusion.`,
        'Professional'
      );
      if (response.success) {
        setFormData(prev => ({
          ...prev,
          content: response.data.content,
          excerpt: response.data.excerpt || prev.excerpt,
          tags: response.data.tags || prev.tags
        }));
        toast.success('Content generated by AI');
      }
    } catch (error) {
      toast.error('Failed to generate content');
    } finally {
      setGeneratingAi(false);
    }
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center h-96">
        <Loader2 className="animate-spin text-brand-blue" size={32} />
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <button 
          onClick={() => navigate('/admin/blogs')}
          className="flex items-center gap-2 text-gray-500 hover:text-gray-900 transition-colors"
        >
          <ArrowLeft size={20} />
          <span>Back to Blogs</span>
        </button>
        <div className="flex gap-3">
          <button 
            type="button"
            className="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded-xl font-medium flex items-center gap-2"
          >
            <Eye size={18} />
            Preview
          </button>
          <button 
            onClick={handleSubmit}
            className="px-6 py-2 bg-brand-dark text-white rounded-xl font-medium hover:bg-brand-blue transition-colors flex items-center gap-2"
          >
            <Save size={18} />
            {id ? 'Update Post' : 'Publish Post'}
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Editor */}
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm">
            <input 
              type="text" 
              placeholder="Post Title" 
              value={formData.title}
              onChange={(e) => setFormData({...formData, title: e.target.value})}
              className="w-full text-3xl font-bold placeholder-gray-300 border-none focus:ring-0 p-0 mb-4"
            />
            
            <div className="flex items-center gap-4 mb-6">
              <button 
                type="button"
                onClick={handleGenerateContent}
                disabled={generatingAi}
                className="flex items-center gap-2 text-sm text-brand-blue bg-blue-50 px-3 py-1.5 rounded-lg hover:bg-blue-100 transition-colors disabled:opacity-50"
              >
                {generatingAi ? <Loader2 size={14} className="animate-spin" /> : <Sparkles size={14} />}
                Generate with AI
              </button>
            </div>

            <textarea 
              placeholder="Write your story..." 
              value={formData.content}
              onChange={(e) => setFormData({...formData, content: e.target.value})}
              className="w-full min-h-[500px] resize-none border-none focus:ring-0 p-0 text-lg text-gray-700 leading-relaxed"
            />
          </div>
        </div>

        {/* Sidebar Settings */}
        <div className="space-y-6">
          <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm space-y-6">
            <h3 className="font-bold text-gray-900">Post Settings</h3>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Status</label>
              <select 
                value={formData.status}
                onChange={(e) => setFormData({...formData, status: e.target.value as any})}
                className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-brand-blue/20 outline-none"
              >
                <option value="draft">Draft</option>
                <option value="published">Published</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Category</label>
              <select 
                value={formData.category}
                onChange={(e) => setFormData({...formData, category: e.target.value})}
                className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-brand-blue/20 outline-none"
              >
                <option value="">Select Category</option>
                <option value="Technology">Technology</option>
                <option value="Design">Design</option>
                <option value="Business">Business</option>
                <option value="Tutorial">Tutorial</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Featured Image URL</label>
              <div className="flex gap-2">
                <input 
                  type="text" 
                  value={formData.image}
                  onChange={(e) => setFormData({...formData, image: e.target.value})}
                  className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-brand-blue/20 outline-none"
                  placeholder="https://..."
                />
                <button className="p-2 bg-gray-100 rounded-lg text-gray-600 hover:bg-gray-200">
                  <ImageIcon size={20} />
                </button>
              </div>
              {formData.image && (
                <div className="mt-2 rounded-lg overflow-hidden h-32 border border-gray-200">
                  <img src={formData.image} alt="Preview" className="w-full h-full object-cover" />
                </div>
              )}
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Excerpt</label>
              <textarea 
                rows={3}
                value={formData.excerpt}
                onChange={(e) => setFormData({...formData, excerpt: e.target.value})}
                className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-brand-blue/20 outline-none resize-none text-sm"
                placeholder="Short summary..."
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Tags (comma separated)</label>
              <input 
                type="text" 
                value={formData.tags?.join(', ') || ''}
                onChange={(e) => setFormData({...formData, tags: e.target.value.split(',').map(s => s.trim())})}
                className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-brand-blue/20 outline-none"
                placeholder="tech, ai, future"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BlogEditor;
