import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Plus, 
  Search, 
  Edit2, 
  Trash2, 
  Briefcase, 
  Sparkles,
  X,
  MapPin,
  Clock,
  Loader2
} from 'lucide-react';
import { api } from '../../services/api';
import { toast } from 'react-hot-toast';

interface Career {
  _id: string;
  title: string;
  department: string;
  location: string;
  type: string;
  description: string;
  requirements: string[];
  status: 'active' | 'closed';
}

const CareerManagement: React.FC = () => {
  const [careers, setCareers] = useState<Career[]>([]);
  const [loading, setLoading] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [currentCareer, setCurrentCareer] = useState<Partial<Career>>({});
  const [isEditing, setIsEditing] = useState(false);
  const [generatingAi, setGeneratingAi] = useState(false);

  useEffect(() => {
    fetchCareers();
  }, []);

  const fetchCareers = async () => {
    try {
      const response = await api.getCareers();
      if (response.success) {
        setCareers(response.data);
      }
    } catch (error) {
      console.error('Failed to fetch careers', error);
      toast.error('Failed to load careers');
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id: string) => {
    if (window.confirm('Are you sure you want to delete this position?')) {
      try {
        await api.deleteCareer(id);
        toast.success('Position deleted successfully');
        fetchCareers();
      } catch (error) {
        toast.error('Failed to delete position');
      }
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      if (isEditing && currentCareer._id) {
        await api.updateCareer(currentCareer._id, currentCareer);
        toast.success('Position updated successfully');
      } else {
        await api.createCareer(currentCareer);
        toast.success('Position created successfully');
      }
      setIsModalOpen(false);
      fetchCareers();
    } catch (error) {
      toast.error('Failed to save position');
    }
  };

  const handleGenerateDescription = async () => {
    if (!currentCareer.title || !currentCareer.department) {
      toast.error('Please enter a title and department first');
      return;
    }
    
    setGeneratingAi(true);
    try {
      const response = await api.generateJobDescription(
        currentCareer.title, 
        currentCareer.department, 
        'Mid-Senior' // Default level for now
      );
      if (response.success) {
        setCurrentCareer({ 
            ...currentCareer, 
            description: response.data.description,
            requirements: response.data.requirements 
        });
        toast.success('Job description generated by AI');
      }
    } catch (error) {
      toast.error('Failed to generate description');
    } finally {
      setGeneratingAi(false);
    }
  };

  const openModal = (career?: Career) => {
    if (career) {
      setCurrentCareer(career);
      setIsEditing(true);
    } else {
      setCurrentCareer({ status: 'active', requirements: [] });
      setIsEditing(false);
    }
    setIsModalOpen(true);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Careers</h1>
          <p className="text-gray-500">Manage job openings and applications</p>
        </div>
        <button 
          onClick={() => openModal()}
          className="flex items-center gap-2 bg-brand-dark text-white px-4 py-2 rounded-xl hover:bg-brand-blue transition-colors"
        >
          <Plus size={20} />
          <span>Post Job</span>
        </button>
      </div>

      {/* Filters & Search */}
      <div className="bg-white p-4 rounded-2xl border border-gray-100 flex flex-col md:flex-row gap-4">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
          <input 
            type="text" 
            placeholder="Search positions..." 
            className="w-full pl-10 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-blue/20"
          />
        </div>
        <div className="flex gap-2">
          <select className="px-4 py-2 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none">
            <option value="">All Departments</option>
            <option value="Engineering">Engineering</option>
            <option value="Design">Design</option>
            <option value="Marketing">Marketing</option>
          </select>
          <select className="px-4 py-2 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none">
            <option value="">All Status</option>
            <option value="active">Active</option>
            <option value="closed">Closed</option>
          </select>
        </div>
      </div>

      {/* Careers List */}
      {loading ? (
        <div className="flex justify-center py-12">
          <Loader2 className="animate-spin text-brand-blue" size={32} />
        </div>
      ) : (
        <div className="bg-white rounded-2xl border border-gray-100 overflow-hidden">
          <table className="w-full">
            <thead className="bg-gray-50 border-b border-gray-100">
              <tr>
                <th className="text-left py-4 px-6 text-xs font-bold text-gray-500 uppercase tracking-wider">Position</th>
                <th className="text-left py-4 px-6 text-xs font-bold text-gray-500 uppercase tracking-wider">Department</th>
                <th className="text-left py-4 px-6 text-xs font-bold text-gray-500 uppercase tracking-wider">Location</th>
                <th className="text-left py-4 px-6 text-xs font-bold text-gray-500 uppercase tracking-wider">Status</th>
                <th className="text-right py-4 px-6 text-xs font-bold text-gray-500 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {careers.map((career) => (
                <tr key={career._id} className="hover:bg-gray-50 transition-colors group">
                  <td className="py-4 px-6">
                    <div className="font-bold text-gray-900">{career.title}</div>
                    <div className="text-xs text-gray-500 flex items-center gap-1 mt-1">
                      <Clock size={12} /> {career.type}
                    </div>
                  </td>
                  <td className="py-4 px-6">
                    <span className="px-2 py-1 bg-blue-50 text-blue-600 rounded-md text-xs font-medium">
                      {career.department}
                    </span>
                  </td>
                  <td className="py-4 px-6">
                    <div className="flex items-center gap-1 text-gray-500 text-sm">
                      <MapPin size={14} /> {career.location}
                    </div>
                  </td>
                  <td className="py-4 px-6">
                    <span className={`px-2 py-1 rounded-full text-xs font-bold uppercase tracking-wider ${
                      career.status === 'active' ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-700'
                    }`}>
                      {career.status}
                    </span>
                  </td>
                  <td className="py-4 px-6 text-right">
                    <div className="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                      <button 
                        onClick={() => openModal(career)}
                        className="p-2 hover:bg-gray-100 rounded-lg text-gray-600"
                      >
                        <Edit2 size={16} />
                      </button>
                      <button 
                        onClick={() => handleDelete(career._id)}
                        className="p-2 hover:bg-red-50 rounded-lg text-red-500"
                      >
                        <Trash2 size={16} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Modal */}
      <AnimatePresence>
        {isModalOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
            <motion.div 
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto"
            >
              <div className="p-6 border-b border-gray-100 flex justify-between items-center sticky top-0 bg-white z-10">
                <h2 className="text-xl font-bold text-gray-900">
                  {isEditing ? 'Edit Position' : 'New Position'}
                </h2>
                <button onClick={() => setIsModalOpen(false)} className="p-2 hover:bg-gray-100 rounded-lg">
                  <X size={20} />
                </button>
              </div>
              
              <form onSubmit={handleSubmit} className="p-6 space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Job Title</label>
                    <input 
                      type="text" 
                      required
                      value={currentCareer.title || ''}
                      onChange={(e) => setCurrentCareer({...currentCareer, title: e.target.value})}
                      className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-brand-blue/20 outline-none"
                      placeholder="e.g. Senior Frontend Developer"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Department</label>
                    <select 
                      value={currentCareer.department || ''}
                      onChange={(e) => setCurrentCareer({...currentCareer, department: e.target.value})}
                      className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-brand-blue/20 outline-none"
                    >
                      <option value="">Select Department</option>
                      <option value="Engineering">Engineering</option>
                      <option value="Design">Design</option>
                      <option value="Marketing">Marketing</option>
                      <option value="Product">Product</option>
                    </select>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Location</label>
                    <input 
                      type="text" 
                      value={currentCareer.location || ''}
                      onChange={(e) => setCurrentCareer({...currentCareer, location: e.target.value})}
                      className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-brand-blue/20 outline-none"
                      placeholder="e.g. Remote, New York"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Type</label>
                    <select 
                      value={currentCareer.type || ''}
                      onChange={(e) => setCurrentCareer({...currentCareer, type: e.target.value})}
                      className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-brand-blue/20 outline-none"
                    >
                      <option value="Full-time">Full-time</option>
                      <option value="Part-time">Part-time</option>
                      <option value="Contract">Contract</option>
                    </select>
                  </div>
                </div>

                <div>
                  <div className="flex justify-between items-center mb-2">
                    <label className="block text-sm font-medium text-gray-700">Description</label>
                    <button 
                      type="button"
                      onClick={handleGenerateDescription}
                      disabled={generatingAi}
                      className="text-xs flex items-center gap-1 text-brand-blue hover:text-brand-dark font-medium disabled:opacity-50"
                    >
                      {generatingAi ? <Loader2 size={12} className="animate-spin" /> : <Sparkles size={12} />}
                      Generate with AI
                    </button>
                  </div>
                  <textarea 
                    rows={6}
                    value={currentCareer.description || ''}
                    onChange={(e) => setCurrentCareer({...currentCareer, description: e.target.value})}
                    className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-brand-blue/20 outline-none resize-none"
                    placeholder="Job description..."
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Requirements (comma separated)</label>
                  <input 
                    type="text" 
                    value={currentCareer.requirements?.join(', ') || ''}
                    onChange={(e) => setCurrentCareer({...currentCareer, requirements: e.target.value.split(',').map(s => s.trim())})}
                    className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-brand-blue/20 outline-none"
                    placeholder="e.g. React, TypeScript, Node.js"
                  />
                </div>

                <div className="flex justify-end gap-3 pt-4 border-t border-gray-100">
                  <button 
                    type="button"
                    onClick={() => setIsModalOpen(false)}
                    className="px-6 py-2 text-gray-600 font-medium hover:bg-gray-50 rounded-lg"
                  >
                    Cancel
                  </button>
                  <button 
                    type="submit"
                    className="px-6 py-2 bg-brand-dark text-white font-medium rounded-lg hover:bg-brand-blue transition-colors"
                  >
                    {isEditing ? 'Update Position' : 'Post Position'}
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default CareerManagement;
